### ISSUE TITLE
App is crashing 

### ISSUE THREAD

**Issue by ankitPagalGuy** [seroperson/itstimetoact#1]
Tried running sample app , but it crashed 

Process: com.seroperson.itstimetoact.sample, PID: 18914
                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seroperson.itstimetoact.sample/com.seroperson.itstimetoact.sample.SampleActivity}: java.lang.IllegalStateException: There is nothing to watch
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
                                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:155)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:139)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                                                                                     Caused by: java.lang.IllegalStateException: There is nothing to watch
                                                                                        at com.seroperson.itstimetoact.TimeToAct.watchLastDropped(TimeToAct.java:94)
                                                                                        at com.seroperson.itstimetoact.sample.SampleActivity.onCreate(SampleActivity.java:46)
                                                                                        at android.app.Activity.performCreate(Activity.java:6072)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424) 
                                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:155) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:139) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
09-15 20:36:55.022 18914-18914/com.seroperson.itstimetoact.sample D/AppTracker: App Event: crash

**Comment by seroperson** [comment]
Really don't know how I missed it. Thanks for detection this.
